[project]
name = "delta-stacks"

[contracts.lending-reader-v1]
path = "contracts/lending-reader-v1.clar"
clarity_version = 3
epoch = 3.0

[repl.remote_data]
enabled = true
initial_height = 6972000
api_url = 'https://api.hiro.so'
