[project]
name = "delta-stacks"

[contracts.lending-reader-v3]
path = "contracts/lending-reader-v3.clar"
clarity_version = 3
epoch = 3.0

[contracts.user-reader-v2]
path = "contracts/user-reader-v2.clar"
clarity_version = 3
epoch = 3.0

[contracts.mock-token]
path = "contracts/mock-token.clar"
clarity_version = 3
epoch = 3.0

[contracts.vault-usdcx]
path = "contracts/vault-usdcx.clar"
clarity_version = 3
epoch = 3.0

[contracts.lending-adapter-trait]
path = "contracts/lending-adapter-trait.clar"
clarity_version = 3
epoch = 3.0

[contracts.vault-usdcx-v2]
path = "contracts/vault-usdcx-v2.clar"
clarity_version = 3
epoch = 3.0

[contracts.mock-adapter]
path = "contracts/mock-adapter.clar"
clarity_version = 3
epoch = 3.0

[repl.remote_data]
enabled = true
initial_height = 6972000
api_url = 'https://api.hiro.so'
